<?php
/*
Copyright 2012 DIYthemes, LLC. Patent pending. All rights reserved.
DIYthemes, Thesis, and the Thesis Theme are registered trademarks of DIYthemes, LLC.
License: DIYthemes Software License Agreement
License URI: http://diythemes.com/thesis/rtfm/software-license-agreement/
*/
require_once(TEMPLATEPATH . '/thesis.php');
// WARNING: Unless you just LOVE problems, DO NOT EDIT THIS FILE!